sample = ["T0,C1,A"
          "T0,C2,E"
          "T1,C1,B"
          "T1,C2,B"
          "T2,C1,C"
          "T2,C2,C"
          "T3,C1,D"
          "T3,C2,D"
          "T4,C1,E"
          "T5,C2,A"]
